apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivela.fullname" . }}-backend
  labels:
    {{- include "trivela.labels" . | nindent 4 }}
    component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "trivela.selectorLabels" . | nindent 4 }}
    component: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
