apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivela.fullname" . }}-frontend
  labels:
    {{- include "trivela.labels" . | nindent 4 }}
    component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "trivela.selectorLabels" . | nindent 4 }}
    component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
